language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang

addons:
  apt:
    packages:
      - libjansson-dev
      - libxcb1-dev
      - libxcb-util0-dev
      - libcairo2-dev

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: cmake --build .
