image: Visual Studio 2015

matrix:
    fast_finish: true

cache:
  - c:\Tools\vcpkg\installed

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - vcpkg install cairo:x86-windows
  - vcpkg install jansson:x86-windows
  - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015" -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..

build_script: cmake --build .

